name: governor-broker
version: git
summary: Broker Daemon for Governor Charms
description: |
  Broker Daemon for Governor Charms
base: core20
grade: stable
confinement: strict

apps:
  governor-broker:
    command: bin/python3 $SNAP/bin/broker -p $SNAP_COMMON
    daemon: simple
    restart-condition: always
    plugs:
      - network

parts:
  governor-broker:
    plugin: python
    source: .
    requirements:
      - ./requirements.txt
    python-packages:
      - wheel
      - setuptools
